apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: stage
namePrefix: stage-
labels:
  - pairs:
      env: stage
resources:
  - ../../base
patches:
  - path: patch-env.yaml
    target:
      kind: Deployment
      name: guestbook
